### ISSUE TITLE
How to score with the new BWB?

### ISSUE THREAD

**Issue by mjpost** [EleanorJiang/BlonDe#6]
I would like to score an output on blonde categories, but it's not quite clear how to do this.

The [top-level README](https://github.com/EleanorJiang/BlonDe/blob/main/README.md#annotation-format) describes an annotation format, but that doesn't fit the format of the BWB files: there are no `ner_re.txt` more `an.txt` files, just files of the form `{section}.ref_re.an.txt`. Furthermore there does not appear to be any documentation of the embedded new format.

I suppose I should use BWBReader class to dump the annotation format used by BlonDe. This seems straightforward with the nice reader, but it also introduces an element of error and interpretation that means I can't compare scores to those reported in the paper. It is not clear exactly what you did to compute scores, beyond the note in Table 7 that you computed both F1 and exact-match. For example, are stats computed at the sentence or document level, etc.

Can you share example code that parses `test_with_annotations` to the format used with BlonDe? 

Ideally I would just like to do the following to compare scores:

```
# create input file from BWB/BWB_dataset/test_with_annotations
your_command > input.txt
your_command > ref.txt
your_command > annotations.txt
# (or whatever)

# translate it
cat input.txt | my_decoder > output.txt

# score it with blonde (for all five cats: ambiguity, entity, tense, pronoun, ellipsis)
blonde -r ref.txt -s output.txt -p -ner annotations.txt
```

(Even more ideally, you would provide a system output from the paper, so that I could verify that I have the correct results.)

**Comment by thunder123321** [comment]
I had the same problem; I first run the BWB/BWBReader.py script to get the csv file, then run the evaluation/get_bwb_scores.py script, the following error is reported:

Traceback (most recent call last):
  File "evaluation/get_bwb_scores.py", line 174, in <module>
    main(args)
  File "evaluation/get_bwb_scores.py", line 168, in main
    evaluate = Evaluate(args.data_dir, args.bwb_annotation_dir, args.out_dir, args.tmp_dir, systems, args.df_name)
  File "evaluation/get_bwb_scores.py", line 33, in __init__
    self.entity_counts = get_entity_counts(bwb_annotation_dir)
  File "/home/nihao/nihaonlp2/yuhao/ParroT-master/EVAL_space/BlonDe/BlonDe-main/./BWB/entity.py", line 117, in get_entity_counts
    df = pd.read_csv(entity_list_file, sep='\t')
  File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'BWB/demo_test_with_annotations/entity_dict.csv'

The entity_dict file is missing!
So we run the BWB/entity.py script, using the csv files by BWBReader, and report the following error again:

Traceback (most recent call last):
  File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'is_pronoun'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "BWB/entity.py", line 175, in <module>
    get_entity_dictionary(chs_file,ref_file,entity_dict)
  File "BWB/entity.py", line 49, in get_entity_dictionary
    chs_df = get_entity_df(chs_mention_file)
  File "BWB/entity.py", line 37, in get_entity_df
    df = df[df["is_pronoun"] == False]
  File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'is_pronoun'

**Comment by thunder123321** [comment]
I had the same problem; I first run the BWB/BWBReader.py script to get the csv file, then run the evaluation/get_bwb_scores.py script, the following error is reported:
`Traceback (most recent call last):
File "evaluation/get_bwb_scores.py", line 174, in
main(args)
File "evaluation/get_bwb_scores.py", line 168, in main
evaluate = Evaluate(args.data_dir, args.bwb_annotation_dir, args.out_dir, args.tmp_dir, systems, args.df_name)
File "evaluation/get_bwb_scores.py", line 33, in init
self.entity_counts = get_entity_counts(bwb_annotation_dir)
File "/home/nihao/nihaonlp2/yuhao/ParroT-master/EVAL_space/BlonDe/BlonDe-main/./BWB/entity.py", line 117, in get_entity_counts
df = pd.read_csv(entity_list_file, sep='\t')
File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
return _read(filepath_or_buffer, kwds)
File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
parser = TextFileReader(filepath_or_buffer, **kwds)
File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in init
self._engine = self._make_engine(f, self.engine)
File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
self.handles = get_handle(
File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'BWB/demo_test_with_annotations/entity_dict.csv'`


The entity_dict file is missing!
So we run the BWB/entity.py script, using the csv files by BWBReader, and report the following error again:
`  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'is_pronoun'
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "BWB/entity.py", line 175, in <module>
    get_entity_dictionary(chs_file,ref_file,entity_dict)
  File "BWB/entity.py", line 49, in get_entity_dictionary
    chs_df = get_entity_df(chs_mention_file)
  File "BWB/entity.py", line 37, in get_entity_df
    df = df[df["is_pronoun"] == False]
  File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/nihao/nihaonlp2/condapkg/envs/Parrot/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'is_pronoun'`
